
version: '3.2'

networks:
    fabric:
        external: 
            name: fabric

services:

    ca_org2:
        networks:
            fabric:
                aliases:
                    - ca_org2
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ansible-fabric
        image: hyperledger/fabric-ca:1.4.0
        hostname: ca.org2.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca_org2
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/945a059a749fe789575f7285e0c74ffdb5043e762a90e8359a84332921325bd1_sk
        ports:
            - "8054:7054"   
        command: sh -c 'fabric-ca-server start --ca.certfile $FABRIC_CA_SERVER_CA_CERTFILE --ca.keyfile $FABRIC_CA_SERVER_CA_KEYFILE -b admin:adminpw -d'
        volumes:
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

    couchdb0_org2:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ansible-fabric
        image: hyperledger/fabric-couchdb:latest
        hostname: couchdb0_org2
        networks:
           - fabric

    couchdb1_org2:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ansible-fabric
        image: hyperledger/fabric-couchdb:latest
        hostname: couchdb1_org2
        networks:
           - fabric
