
version: '3.2'

networks:
    skcript:
        external: 
            name: skcript

services:

    ca_org4:
        networks:
            skcript:
                aliases:
                    - ca_org4
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == hades-desktop
        image: hyperledger/fabric-ca:1.3.0
        hostname: ca.org4.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca_org4
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org4.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/7998480b5e5adc89803e8999daca78b74fc186bfa5e824a94d00cd976b4a87a8_sk
        ports:
            - 10054:7054   
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org4.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

    couchdb0_org4:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == hades-desktop
        image: hyperledger/fabric-couchdb:latest
        hostname: couchdb0_org4
        networks:
           - skcript

